### PR TITLE
Setup google cloud run with postgres db

### PR DESCRIPTION
**Pull request by soapy1**

### CODE REVIEW

**Comment by nikovanmeurs** [comment]
Looks pretty good. I'd add two more things to the terraform script: which is to create the database user and the database for the metadata store. Strapi'll need to have some environment variables passed to the container, but we can add those when we have an actual build.

**Comment by soapy1** [comment]
Pushed up some changes.
- I added an additional postgres database for metadata store. Currently, it is not plugged up to anything
- There is a database user for each db instance
- I did not add any kind of secret management thing. Currently the passwords can be set with env vars using `TF_VAR_<variable name>`. Might be nice to use https://github.com/AGWA/git-crypt instead. Will leave that call up to @nikovanmeurs

**Comment by nikovanmeurs** [comment]
It looks like I caused some confunsion with my earlier remark about the metadata database. GCP makes a distinction between databases and database instances. The instance refers to the machine, while the database refers to a database in postgres/mysql (https://cloud.google.com/sql/docs/postgres/create-manage-databases)

**Comment by soapy1** [comment]
@nikovanmeurs ahh, I see. That's my bad, should have read gcp docs better. Thanks for the clarification. Should be good to go now.

**Pull request merged**
